DROP table SIGNATURE;
DROP table DOCUMENT;
DROP table PROFESSEUR;
DROP table ELEVE;
DROP table CALANDRIER;
DROP table GROUPE;
DROP table CLASSE;
DROP table UTILISATEUR;
DROP table ROLE;

CREATE table ROLE
(ID_ROLE INTEGER(20) NOT NULL AUTO_INCREMENT,
STATUT VARCHAR(20),
PRIMARY KEY (ID_ROLE));

CREATE table UTILISATEUR
(ID_UTILISATEUR INTEGER(20) NOT NULL AUTO_INCREMENT,
NOM VARCHAR(20),
PRENOM VARCHAR(20),
EMAIL VARCHAR(20),
MotDePasse VARCHAR(20),
ID_ROLE INTEGER(20),
PRIMARY KEY (ID_UTILISATEUR),
FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID_ROLE));

CREATE table CLASSE
(ID_CLASSE INTEGER(20) NOT NULL AUTO_INCREMENT,
PRIMARY KEY (ID_CLASSE));

CREATE table GROUPE
(ID_GROUPE INTEGER(20) NOT NULL AUTO_INCREMENT,
ID_CLASSE INTEGER(20),
PRIMARY KEY (ID_GROUPE),
FOREIGN KEY (ID_CLASSE) REFERENCES CLASSE(ID_CLASSE));

CREATE table CALANDRIER 
(ID_CALANDRIER INTEGER(20) NOT NULL AUTO_INCREMENT,
HEUR DATE,
ID_CLASSE INTEGER(20),
ID_GROUPE INTEGER(20),
PRIMARY KEY (ID_CALANDRIER),
FOREIGN KEY (ID_CLASSE) REFERENCES CLASSE(ID_CLASSE),
FOREIGN KEY (ID_GROUPE) REFERENCES GROUPE(ID_GROUPE));

CREATE table ELEVE
(ID_ELEVE INTEGER(20) NOT NULL AUTO_INCREMENT,
ID_CLASSE INTEGER(20),
ID_GROUPE INTEGER(20),
ID_CALANDRIER INTEGER(20),
ID_ROLE INTEGER(20),
ID_UTILISATEUR INTEGER(20),
PRIMARY KEY (ID_ELEVE),
FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR),
FOREIGN KEY (ID_CLASSE) REFERENCES CLASSE(ID_CLASSE),
FOREIGN KEY (ID_GROUPE) REFERENCES GROUPE(ID_GROUPE),
FOREIGN KEY (ID_CALANDRIER) REFERENCES CALANDRIER(ID_CALANDRIER),
FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID_ROLE));

CREATE table PROFESSEUR
(ID_PROFESSEUR INTEGER(20) NOT NULL AUTO_INCREMENT,
ID_CALANDRIER INTEGER(20),
ID_ROLE INTEGER(20),
ID_UTILISATEUR INTEGER(20),
PRIMARY KEY (ID_PROFESSEUR),
FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR),
FOREIGN KEY (ID_CALANDRIER ) REFERENCES CALANDRIER (ID_CALANDRIER),
FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID_ROLE));

CREATE table DOCUMENT
(ID_DOCUMENT INTEGER(20) NOT NULL AUTO_INCREMENT,
VALID BOOLEAN,
PRIMARY KEY (ID_DOCUMENT));

CREATE table SIGNATURE
(ID_SIGNATURE INTEGER(20) NOT NULL AUTO_INCREMENT,
ID_ROLE INTEGER(20),
ID_DOCUMENT INTEGER(20),
VALID BOOLEAN,
ID_UTILISATEUR INTEGER(20),
ID_CALANDRIER INTEGER(20),
PRIMARY KEY (ID_SIGNATURE),
FOREIGN KEY (ID_UTILISATEUR) REFERENCES UTILISATEUR(ID_UTILISATEUR),
FOREIGN KEY (ID_CALANDRIER) REFERENCES CALANDRIER(ID_CALANDRIER),
FOREIGN KEY (ID_ROLE) REFERENCES ROLE(ID_ROLE),
FOREIGN KEY (ID_DOCUMENT) REFERENCES DOCUMENT(ID_DOCUMENT));
